### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gregbenner** [nuxt-company/demo-blog-nuxt-content#14]
Really cool starter project and blog, thank you

Just wondering what the search function does, I tried a few things like article title, article content and author and none of them seemed to work.

![Screenshot from 2020-08-14 19-36-48](https://user-images.githubusercontent.com/1177690/90299860-bd775900-de65-11ea-91f4-466068bf6fb3.png)
![Screenshot from 2020-08-14 19-36-32](https://user-images.githubusercontent.com/1177690/90299861-be0fef80-de65-11ea-8513-2ad16e158e97.png)
![Screenshot from 2020-08-14 19-36-07](https://user-images.githubusercontent.com/1177690/90299862-bea88600-de65-11ea-86df-10e1ae998936.png)

**Comment by debs-obrien** [comment]
hi, yes as it is a demo project I only set up the search for article title. so that is all it will search for but you can easily modify it to search for author, content etc. so yes basically what you see in the example if you click on one of the links in green it will take you to that article as it is in the title of the article.
